[package]
name = "motion-media"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
motion-model = { path = "../motion-model" }
serde.workspace = true
serde_json.workspace = true
fs2 = "0.4.3"
symphonia = { version = "=0.5.5", default-features = false, features = ["aac", "mp3", "isomp4", "wav", "pcm", "flac", "alac", "vorbis", "ogg", "aiff"] }
fontdue = { version = "=0.9.4", default-features = false, features = ["std"] }
sha2 = "0.10"

[dev-dependencies]
motion-core = { path = "../motion-core" }
motion-render = { path = "../motion-render" }
zip = { version = "2.4", default-features = false, features = ["deflate"] }
tempfile = "3"
