[package]
name = "motion-effects"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
naga = { version = "=24.0.0", features = ["wgsl-in", "glsl-out"] }
sha2 = "0.10"
semver = "1.0"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
image.workspace = true
regex = "1.10"

[dev-dependencies]
tempfile = "3.17"
