//! Native GPU rendering. Image decoding/upload happens on resource changes;
//! playback uploads only fixed-size layer uniforms.
mod effect_gpu;
pub mod effect_plan;
pub mod resource_policy;
mod effect_plan_cache;
pub mod composition_plan;
mod measurement;
mod presenter;
mod quality;
mod renderer;
pub mod image_resources;
pub mod scene_generator;
mod particle_emitter;
mod timing;
mod video_pixels;
mod video_gpu;
mod vector_mesh;
mod layer_gpu;
pub mod mask_plan;
pub mod compositing_plan;
mod compositing_gpu;
mod mask_gpu;
pub use video_pixels::{ChromaLayout, VideoPlane, Yuv420Frame};
pub use measurement::{FrameMeasurement, FrameRecorder};
pub use presenter::Presenter;
pub use quality::{PreviewMode, PreviewPolicy, PreviewTier};
pub use renderer::premultiply_pixels;
pub use renderer::{CaptureTarget, RenderError, RenderStats, RenderTarget, Renderer};
pub use timing::{GpuTimer, GpuTiming};

mod scene;
mod compositor;
pub mod selection_geometry;
pub mod position_path;
pub use scene::{DrawLayer, HitCandidate, NestedScene, Scene};
pub use compositor::{PlaneBatch, PlaneCompositor, PlaneVertex};
