//! Native GPU rendering. Image decoding/upload happens on resource changes;
//! playback uploads only fixed-size layer uniforms.
mod effect_gpu;
pub mod effect_plan;
mod measurement;
mod presenter;
mod quality;
mod renderer;
pub mod scene_generator;
mod timing;
mod video_pixels;
mod video_gpu;
pub use video_pixels::{VideoPlane, Yuv420Frame};
pub use aem_core::Scene;
pub use measurement::{FrameMeasurement, FrameRecorder};
pub use presenter::Presenter;
pub use quality::{PreviewMode, PreviewPolicy, PreviewTier};
pub use renderer::premultiply_pixels;
pub use renderer::{CaptureTarget, RenderError, RenderStats, RenderTarget, Renderer};
pub use timing::{GpuTimer, GpuTiming};
