"""Compare actual Android frames against ffmpeg at the reported source PTS.

Fixtures are generated by this project. Evidence stays outside the Git tree.
No decoder is mocked: adb obtains the real JNI output from instrumented tests.
"""
import argparse
from decimal import Decimal
import json
from pathlib import Path
import subprocess


def run(*args):
    return subprocess.check_output(args)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--adb", required=True)
    parser.add_argument("--serial", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--remote-project", action="append")
    parser.add_argument("--latest-per-fixture", action="store_true",
                        help="Use the newest completed report for each fixture; check instrumentation separately")
    args = parser.parse_args()
    adb = [args.adb, "-s", args.serial, "exec-out", "run-as", "com.motionstudio.editor"]
    roots = args.remote_project or [str(Path(p).parent).replace("\\", "/") for p in run(
        *adb, "find", "files/acceptance", "-name", "video-report.json"
    ).decode().splitlines()]
    fixtures = Path(__file__).resolve().parents[1] / "crates/motion-media/tests/fixtures/video"
    manifest = json.loads((fixtures / "manifest.json").read_text())
    if args.latest_per_fixture:
        latest = {}
        for root in roots:
            r = json.loads(run(*adb, "cat", root + "/video-report.json"))
            v = r["metadata"]["video"]
            key = (v["variable_frame_rate"], v["rotation"])
            stamp = int(run(*adb,"stat","-c","%Y",root+"/video-report.json"))
            if key not in latest or stamp > latest[key][0]: latest[key] = (stamp,root)
        roots = [v[1] for v in latest.values()]
    results = []
    for root in roots:
        report_bytes = run(*adb, "cat", root + "/video-report.json")
        report = json.loads(report_bytes)
        video = report["metadata"]["video"]
        dst = args.output / root.split("/")[-1]
        dst.mkdir(parents=True, exist_ok=True)
        (dst / "video-report.json").write_bytes(report_bytes)
        if video["variable_frame_rate"]:
            name = "variable.mp4"
        elif video["rotation"] == 90:
            name = "rotated-90.mp4"
        else:
            name = "silent-24fps.mp4"
        pts = [int(Decimal(f["best_effort_timestamp_time"]) * 1_000_000)
               for f in manifest[name]["frames"]]
        for index, sample in enumerate(report["samples"]):
            if name == "silent-24fps.mp4" and index != 1:
                continue  # Only the .75s frame was written by this test.
            leaf = "silent-075.rgba" if name == "silent-24fps.mp4" else f"{name}-{index}.rgba"
            pixels = run(*adb, "cat", root + "/" + leaf)
            (dst / leaf).write_bytes(pixels)
            source_index = pts.index(sample["pts_us"])
            oracle = run("ffmpeg", "-v", "error", "-i", str(fixtures / name), "-vf",
                         f"select=eq(n\\,{source_index})", "-frames:v", "1", "-f", "rawvideo",
                         "-pix_fmt", "rgba", "pipe:1")
            assert len(pixels) == len(oracle) == sample["width"] * sample["height"] * 4
            assert source_index + 1 == len(pts) or sample["end_us"] == pts[source_index + 1]
            diffs = [abs(pixels[n] - oracle[n]) for n in range(len(pixels)) if n % 4 != 3]
            ordered = sorted(diffs)
            result = {"source": name, "source_frame": source_index, "pts_us": sample["pts_us"],
                      "width": sample["width"], "height": sample["height"],
                      "source_transfer": sample["source_transfer"], "decoder": sample["decoder"],
                      "mean_absolute_rgb_error": sum(diffs) / len(diffs),
                      "rms_rgb_error": (sum(d*d for d in diffs) / len(diffs)) ** .5,
                      "p99_absolute_rgb_error": ordered[int(len(diffs)*.99)],
                      "max_absolute_rgb_error": max(diffs), "decode_us": sample["decode_us"]}
            # Edges differ between chroma upsamplers. Large colour/rotation errors still fail.
            assert result["mean_absolute_rgb_error"] < 8, result
            assert result["p99_absolute_rgb_error"] < 35, result
            results.append(result)
    assert results, "No frames compared"
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "comparison.json").write_text(json.dumps(results, indent=2) + "\n")
    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
